### PR TITLE
Add installation instructions

### PR DESCRIPTION
**Pull request by ValdoTR**
As some users are not confortable with web development, I added an 'Installation' section in the README.

### CODE REVIEW

**Comment by moufmouf** [comment]
Hey @ValdoTR ,

I think we should really choose either NPM or Yarn (I'd go with NPM since it is targetted at a wide population that does not necessarily have Yarn).

I'm saying this because we have both a `package-lock.json` and a `yarn.lock` and that makes no sense (especially since they are not in sync).
We should remove the yarn.lock completely and only refer to npm instructions.

Also: installation instructions are already present at https://workadventu.re/map-building .
Do we really need to add them here?

**Comment by ValdoTR** [comment]
Hi @moufmouf,

I removed the instructions about yarn and ignored the yarn.lock file git in order to let users use yarn without issues.

About the doc that is already in the website, you are right but, it's just two lines of code and I don't think this will change so why not? :)

**Comment by moufmouf** [comment]
I think we should remove yarn.lock before adding it to gitignore. Otherwise, we won't be able to delete it later

**Comment by ValdoTR** [comment]
Oh... sorry my bad.

**Pull request merged**
